package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.circleranking.CircleRankingService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class CircleRankingServiceImpl extends io.renagc.awanotsu.proto.circleranking.CircleRankingServiceGrpc.CircleRankingServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(CircleRankingServiceImpl.class);

    private final ServerContext ctx;

    public CircleRankingServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void getCircleRanking(com.google.protobuf.Empty request, StreamObserver<io.renagc.awanotsu.proto.circleranking.GetCircleRankingResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.circleranking.GetCircleRankingResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
