package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.circlerankupreward.CircleRankUpRewardService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class CircleRankUpRewardServiceImpl extends io.renagc.awanotsu.proto.circlerankupreward.CircleRankUpRewardServiceGrpc.CircleRankUpRewardServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(CircleRankUpRewardServiceImpl.class);

    private final ServerContext ctx;

    public CircleRankUpRewardServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void getCircleRankUpRewardReceived(com.google.protobuf.Empty request, StreamObserver<io.renagc.awanotsu.proto.circlerankupreward.GetCircleRankUpRewardReceivedResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.circlerankupreward.GetCircleRankUpRewardReceivedResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void receiveCircleRankUpReward(com.google.protobuf.Empty request, StreamObserver<io.renagc.awanotsu.proto.circlerankupreward.ReceiveCircleRankUpRewardResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.circlerankupreward.ReceiveCircleRankUpRewardResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
