package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.circleplayer.CirclePlayerService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class CirclePlayerServiceImpl extends io.renagc.awanotsu.proto.circleplayer.CirclePlayerServiceGrpc.CirclePlayerServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(CirclePlayerServiceImpl.class);

    private final ServerContext ctx;

    public CirclePlayerServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void autoTransferMaster(com.google.protobuf.Empty request, StreamObserver<io.renagc.awanotsu.proto.circleplayer.AutoTransferMasterResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.circleplayer.AutoTransferMasterResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
