package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.content_unlock.ContentUnlockService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class ContentUnlockServiceImpl extends io.renagc.awanotsu.proto.content_unlock.ContentUnlockServiceGrpc.ContentUnlockServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(ContentUnlockServiceImpl.class);

    private final ServerContext ctx;

    public ContentUnlockServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void shown(io.renagc.awanotsu.proto.content_unlock.ShownRequest request, StreamObserver<io.renagc.awanotsu.proto.content_unlock.ShownResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.content_unlock.ShownResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
