package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.debug.DebugService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class DebugServiceImpl extends io.renagc.awanotsu.proto.debug.DebugServiceGrpc.DebugServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(DebugServiceImpl.class);

    private final ServerContext ctx;

    public DebugServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void addCircleTotalPoint(io.renagc.awanotsu.proto.debug.AddCircleTotalPointRequest request, StreamObserver<io.renagc.awanotsu.proto.debug.AddCircleTotalPointResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.debug.AddCircleTotalPointResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void addPlayerCirclePoint(io.renagc.awanotsu.proto.debug.AddPlayerCirclePointRequest request, StreamObserver<com.google.protobuf.Empty> responseObserver) {
        responseObserver.onNext(com.google.protobuf.Empty.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void deleteWithdrawal(io.renagc.awanotsu.proto.debug.DeleteWithdrawalRequest request, StreamObserver<io.renagc.awanotsu.proto.debug.DeleteWithdrawalResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.debug.DeleteWithdrawalResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void empty(com.google.protobuf.Empty request, StreamObserver<io.renagc.awanotsu.proto.debug.EmptyResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.debug.EmptyResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void gainCharacterFriendshipRankExp(io.renagc.awanotsu.proto.debug.GainCharacterFriendshipRankExpRequest request, StreamObserver<io.renagc.awanotsu.proto.debug.GainCharacterFriendshipRankExpResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.debug.GainCharacterFriendshipRankExpResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void gainCharacterRankExp(io.renagc.awanotsu.proto.debug.GainCharacterRankExpRequest request, StreamObserver<io.renagc.awanotsu.proto.debug.GainCharacterRankExpResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.debug.GainCharacterRankExpResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void gainGem(io.renagc.awanotsu.proto.debug.GainGemRequest request, StreamObserver<io.renagc.awanotsu.proto.debug.GainGemResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.debug.GainGemResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void gainItem(io.renagc.awanotsu.proto.debug.GainItemRequest request, StreamObserver<io.renagc.awanotsu.proto.debug.GainItemResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.debug.GainItemResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void gainMemberCard(io.renagc.awanotsu.proto.debug.GainMemberCardRequest request, StreamObserver<io.renagc.awanotsu.proto.debug.GainMemberCardResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.debug.GainMemberCardResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void gainMusic(io.renagc.awanotsu.proto.debug.GainMusicRequest request, StreamObserver<io.renagc.awanotsu.proto.debug.GainMusicResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.debug.GainMusicResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void gainPlayerRankExp(io.renagc.awanotsu.proto.debug.GainPlayerRankExpRequest request, StreamObserver<io.renagc.awanotsu.proto.debug.GainPlayerRankExpResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.debug.GainPlayerRankExpResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void gainSupportCard(io.renagc.awanotsu.proto.debug.GainSupportCardRequest request, StreamObserver<io.renagc.awanotsu.proto.debug.GainSupportCardResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.debug.GainSupportCardResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void postPresent(io.renagc.awanotsu.proto.debug.PostPresentRequest request, StreamObserver<io.renagc.awanotsu.proto.debug.PostPresentResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.debug.PostPresentResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void resetCircleRank(io.renagc.awanotsu.proto.debug.ResetCircleRankRequest request, StreamObserver<io.renagc.awanotsu.proto.debug.ResetCircleRankResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.debug.ResetCircleRankResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void resetCircleRankUpRewardReceived(io.renagc.awanotsu.proto.debug.ResetCircleRankUpRewardReceivedRequest request, StreamObserver<io.renagc.awanotsu.proto.debug.ResetCircleRankUpRewardReceivedResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.debug.ResetCircleRankUpRewardReceivedResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void updateAllCircleMasterLoginAt(io.renagc.awanotsu.proto.debug.UpdateAllCircleMasterLoginAtRequest request, StreamObserver<com.google.protobuf.Empty> responseObserver) {
        responseObserver.onNext(com.google.protobuf.Empty.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void updateAllCircleMissionCounter(io.renagc.awanotsu.proto.debug.UpdateAllCircleMissionCounterRequest request, StreamObserver<com.google.protobuf.Empty> responseObserver) {
        responseObserver.onNext(com.google.protobuf.Empty.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void updateCircleMissionCounter(io.renagc.awanotsu.proto.debug.UpdateCircleMissionCounterRequest request, StreamObserver<com.google.protobuf.Empty> responseObserver) {
        responseObserver.onNext(com.google.protobuf.Empty.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void updateLoginbonus(io.renagc.awanotsu.proto.debug.UpdateLoginbonusRequest request, StreamObserver<com.google.protobuf.Empty> responseObserver) {
        responseObserver.onNext(com.google.protobuf.Empty.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void updateMission(io.renagc.awanotsu.proto.debug.UpdateMissionRequest request, StreamObserver<com.google.protobuf.Empty> responseObserver) {
        responseObserver.onNext(com.google.protobuf.Empty.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void updateMissionCounter(io.renagc.awanotsu.proto.debug.UpdateMissionCounterRequest request, StreamObserver<com.google.protobuf.Empty> responseObserver) {
        responseObserver.onNext(com.google.protobuf.Empty.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void updateShop(io.renagc.awanotsu.proto.debug.UpdateShopRequest request, StreamObserver<com.google.protobuf.Empty> responseObserver) {
        responseObserver.onNext(com.google.protobuf.Empty.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void updateSupportCard(io.renagc.awanotsu.proto.debug.UpdateSupportCardRequest request, StreamObserver<com.google.protobuf.Empty> responseObserver) {
        responseObserver.onNext(com.google.protobuf.Empty.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
