package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.deck.DeckService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class DeckServiceImpl extends io.renagc.awanotsu.proto.deck.DeckServiceGrpc.DeckServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(DeckServiceImpl.class);

    private final ServerContext ctx;

    public DeckServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void saveDecks(io.renagc.awanotsu.proto.deck.SaveDecksRequest request, StreamObserver<io.renagc.awanotsu.proto.deck.SaveDecksResponse> responseObserver) {
        io.renagc.awanotsu.flow.Flows.saveDecks(ctx, request, responseObserver);
    }

}
