package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.event.EventService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class EventServiceImpl extends io.renagc.awanotsu.proto.event.EventServiceGrpc.EventServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(EventServiceImpl.class);

    private final ServerContext ctx;

    public EventServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void executeBoxGacha(io.renagc.awanotsu.proto.event.ExecuteBoxGachaRequest request, StreamObserver<io.renagc.awanotsu.proto.event.ExecuteBoxGachaResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.event.ExecuteBoxGachaResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void getRank(io.renagc.awanotsu.proto.event.GetRankRequest request, StreamObserver<io.renagc.awanotsu.proto.event.GetRankResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.event.GetRankResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void getRankingList(io.renagc.awanotsu.proto.event.GetRankingListRequest request, StreamObserver<io.renagc.awanotsu.proto.event.GetRankingListResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.event.GetRankingListResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void resetBoxGacha(io.renagc.awanotsu.proto.event.ResetBoxGachaRequest request, StreamObserver<io.renagc.awanotsu.proto.event.ResetBoxGachaResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.event.ResetBoxGachaResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
