package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.exchange.ExchangeService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class ExchangeServiceImpl extends io.renagc.awanotsu.proto.exchange.ExchangeServiceGrpc.ExchangeServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(ExchangeServiceImpl.class);

    private final ServerContext ctx;

    public ExchangeServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void exchange(io.renagc.awanotsu.proto.exchange.ExchangeRequest request, StreamObserver<io.renagc.awanotsu.proto.exchange.ExchangeResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.exchange.ExchangeResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
