package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.external_payments.ExternalPaymentsService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class ExternalPaymentsServiceImpl extends io.renagc.awanotsu.proto.external_payments.ExternalPaymentsServiceGrpc.ExternalPaymentsServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(ExternalPaymentsServiceImpl.class);

    private final ServerContext ctx;

    public ExternalPaymentsServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void executePayment(io.renagc.awanotsu.proto.external_payments.ExecutePaymentRequest request, StreamObserver<io.renagc.awanotsu.proto.external_payments.ExecutePaymentResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.external_payments.ExecutePaymentResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void itemStatus(io.renagc.awanotsu.proto.external_payments.ItemStatusRequest request, StreamObserver<io.renagc.awanotsu.proto.external_payments.ItemStatusResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.external_payments.ItemStatusResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void unlinkPlayer(io.renagc.awanotsu.proto.external_payments.UnlinkPlayerRequest request, StreamObserver<io.renagc.awanotsu.proto.external_payments.UnlinkPlayerResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.external_payments.UnlinkPlayerResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void nop(com.google.protobuf.Empty request, StreamObserver<com.google.protobuf.Empty> responseObserver) {
        responseObserver.onNext(com.google.protobuf.Empty.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
