package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.friend.FriendService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class FriendServiceImpl extends io.renagc.awanotsu.proto.friend.FriendServiceGrpc.FriendServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(FriendServiceImpl.class);

    private final ServerContext ctx;

    public FriendServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void findByProfileID(io.renagc.awanotsu.proto.friend.FindByProfileIDRequest request, StreamObserver<io.renagc.awanotsu.proto.friend.FindByProfileIDResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.friend.FindByProfileIDResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void friendAnswer(io.renagc.awanotsu.proto.friend.FriendAnswerRequest request, StreamObserver<io.renagc.awanotsu.proto.friend.FriendAnswerResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.friend.FriendAnswerResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void friendApproval(io.renagc.awanotsu.proto.friend.FriendApprovalRequest request, StreamObserver<io.renagc.awanotsu.proto.friend.FriendApprovalResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.friend.FriendApprovalResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void friendRequestWithdrawal(io.renagc.awanotsu.proto.friend.FriendRequestWithdrawalRequest request, StreamObserver<io.renagc.awanotsu.proto.friend.FriendRequestWithdrawalResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.friend.FriendRequestWithdrawalResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void friendUnlink(io.renagc.awanotsu.proto.friend.FriendUnlinkRequest request, StreamObserver<io.renagc.awanotsu.proto.friend.FriendUnlinkResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.friend.FriendUnlinkResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void playerReport(io.renagc.awanotsu.proto.friend.PlayerReportRequest request, StreamObserver<io.renagc.awanotsu.proto.friend.PlayerReportResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.friend.PlayerReportResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
