package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.gacha.GachaService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class GachaServiceImpl extends io.renagc.awanotsu.proto.gacha.GachaServiceGrpc.GachaServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(GachaServiceImpl.class);

    private final ServerContext ctx;

    public GachaServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void checkMaintenanceGacha(io.renagc.awanotsu.proto.gacha.CheckMaintenanceGachaRequest request, StreamObserver<io.renagc.awanotsu.proto.gacha.CheckMaintenanceGachaResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.gacha.CheckMaintenanceGachaResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void convertPoint(io.renagc.awanotsu.proto.gacha.ConvertPointRequest request, StreamObserver<io.renagc.awanotsu.proto.gacha.ConvertPointResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.gacha.ConvertPointResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void execute(io.renagc.awanotsu.proto.gacha.ExecuteRequest request, StreamObserver<io.renagc.awanotsu.proto.gacha.ExecuteResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.gacha.ExecuteResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void history(io.renagc.awanotsu.proto.gacha.HistoryRequest request, StreamObserver<io.renagc.awanotsu.proto.gacha.HistoryResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.gacha.HistoryResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
