package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.home.HomeService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class HomeServiceImpl extends io.renagc.awanotsu.proto.home.HomeServiceGrpc.HomeServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(HomeServiceImpl.class);

    private final ServerContext ctx;

    public HomeServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void get(io.renagc.awanotsu.proto.home.GetHomeRequest request, StreamObserver<io.renagc.awanotsu.proto.home.GetHomeResponse> responseObserver) {
        io.renagc.awanotsu.flow.Flows.getHome(ctx, request, responseObserver);
    }

}
