package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.invitation.InvitationService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class InvitationServiceImpl extends io.renagc.awanotsu.proto.invitation.InvitationServiceGrpc.InvitationServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(InvitationServiceImpl.class);

    private final ServerContext ctx;

    public InvitationServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void generateInvitationCode(io.renagc.awanotsu.proto.invitation.GenerateInvitationCodeRequest request, StreamObserver<io.renagc.awanotsu.proto.invitation.GenerateInvitationCodeResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.invitation.GenerateInvitationCodeResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void inputInvitationCode(io.renagc.awanotsu.proto.invitation.InputInvitationCodeRequest request, StreamObserver<io.renagc.awanotsu.proto.invitation.InputInvitationCodeResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.invitation.InputInvitationCodeResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void updateInvitationView(io.renagc.awanotsu.proto.invitation.UpdateInvitationViewRequest request, StreamObserver<io.renagc.awanotsu.proto.invitation.UpdateInvitationViewResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.invitation.UpdateInvitationViewResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
