package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.livemusic.LiveMusicService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class LiveMusicServiceImpl extends io.renagc.awanotsu.proto.livemusic.LiveMusicServiceGrpc.LiveMusicServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(LiveMusicServiceImpl.class);

    private final ServerContext ctx;

    public LiveMusicServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void getRanking(io.renagc.awanotsu.proto.livemusic.GetRankingRequest request, StreamObserver<io.renagc.awanotsu.proto.livemusic.GetRankingResponse> responseObserver) {
        io.renagc.awanotsu.flow.Flows.getRanking(ctx, request, responseObserver);
    }

    @Override
    public void saveFavorite(io.renagc.awanotsu.proto.livemusic.SaveFavoriteRequest request, StreamObserver<io.renagc.awanotsu.proto.livemusic.SaveFavoriteResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.livemusic.SaveFavoriteResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
