package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.liveboost.LiveBoostService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class LiveBoostServiceImpl extends io.renagc.awanotsu.proto.liveboost.LiveBoostServiceGrpc.LiveBoostServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(LiveBoostServiceImpl.class);

    private final ServerContext ctx;

    public LiveBoostServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void liveBoostHelp(io.renagc.awanotsu.proto.liveboost.LiveBoostHelpRequest request, StreamObserver<com.google.protobuf.Empty> responseObserver) {
        responseObserver.onNext(com.google.protobuf.Empty.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void liveBoostRecovery(io.renagc.awanotsu.proto.liveboost.LiveBoostRecoveryRequest request, StreamObserver<io.renagc.awanotsu.proto.liveboost.LiveBoostRecoveryResponse> responseObserver) {
        io.renagc.awanotsu.flow.Flows.liveBoostRecovery(ctx, request, responseObserver);
    }

    @Override
    public void liveBoostReqCheck(com.google.protobuf.Empty request, StreamObserver<io.renagc.awanotsu.proto.liveboost.LiveBoostReqCheckResponse> responseObserver) {
        io.renagc.awanotsu.flow.Flows.liveBoostReqCheck(ctx, request, responseObserver);
    }

}
