package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.live.LiveService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class LiveServiceImpl extends io.renagc.awanotsu.proto.live.LiveServiceGrpc.LiveServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(LiveServiceImpl.class);

    private final ServerContext ctx;

    public LiveServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void checkMaintenanceCasualMatch(io.renagc.awanotsu.proto.live.CheckMaintenanceCasualMatchRequest request, StreamObserver<io.renagc.awanotsu.proto.live.CheckMaintenanceCasualMatchResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.live.CheckMaintenanceCasualMatchResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void checkMaintenanceRankMatch(io.renagc.awanotsu.proto.live.CheckMaintenanceRankMatchRequest request, StreamObserver<io.renagc.awanotsu.proto.live.CheckMaintenanceRankMatchResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.live.CheckMaintenanceRankMatchResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void finishBattleLive(io.renagc.awanotsu.proto.live.FinishBattleLiveRequest request, StreamObserver<io.renagc.awanotsu.proto.live.FinishBattleLiveResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.live.FinishBattleLiveResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void finishFree(io.renagc.awanotsu.proto.live.FinishFreeRequest request, StreamObserver<io.renagc.awanotsu.proto.live.FinishFreeResponse> responseObserver) {
        io.renagc.awanotsu.flow.Flows.finishFree(ctx, request, responseObserver);
    }

    @Override
    public void gainStampReward(io.renagc.awanotsu.proto.live.GainStampRewardRequest request, StreamObserver<io.renagc.awanotsu.proto.live.GainStampRewardResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.live.GainStampRewardResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void getBattleLiveResult(io.renagc.awanotsu.proto.live.GetBattleLiveResultRequest request, StreamObserver<io.renagc.awanotsu.proto.live.GetBattleLiveResultResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.live.GetBattleLiveResultResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void getBattleLiveSearchId(io.renagc.awanotsu.proto.live.GetBattleLiveSearchIdRequest request, StreamObserver<io.renagc.awanotsu.proto.live.GetBattleLiveSearchIdResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.live.GetBattleLiveSearchIdResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void saveSetting(io.renagc.awanotsu.proto.live.SaveSettingRequest request, StreamObserver<io.renagc.awanotsu.proto.live.SaveSettingResponse> responseObserver) {
        io.renagc.awanotsu.flow.Flows.saveSetting(ctx, request, responseObserver);
    }

    @Override
    public void skipFree(io.renagc.awanotsu.proto.live.SkipFreeRequest request, StreamObserver<io.renagc.awanotsu.proto.live.SkipFreeResponse> responseObserver) {
        io.renagc.awanotsu.flow.Flows.skipFree(ctx, request, responseObserver);
    }

    @Override
    public void startBattleLive(io.renagc.awanotsu.proto.live.StartBattleLiveRequest request, StreamObserver<io.renagc.awanotsu.proto.live.StartBattleLiveResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.live.StartBattleLiveResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void startFree(io.renagc.awanotsu.proto.live.StartFreeRequest request, StreamObserver<io.renagc.awanotsu.proto.live.StartFreeResponse> responseObserver) {
        io.renagc.awanotsu.flow.Flows.startFree(ctx, request, responseObserver);
    }

}
