package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.loginbonus.LoginBonusService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class LoginBonusServiceImpl extends io.renagc.awanotsu.proto.loginbonus.LoginBonusServiceGrpc.LoginBonusServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(LoginBonusServiceImpl.class);

    private final ServerContext ctx;

    public LoginBonusServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void updateLoginbonus(io.renagc.awanotsu.proto.loginbonus.UpdateLoginbonusRequest request, StreamObserver<io.renagc.awanotsu.proto.loginbonus.UpdateLoginbonusResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.loginbonus.UpdateLoginbonusResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
