package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.masterdata.MasterdataService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class MasterdataServiceImpl extends io.renagc.awanotsu.proto.masterdata.MasterdataServiceGrpc.MasterdataServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(MasterdataServiceImpl.class);

    private final ServerContext ctx;

    public MasterdataServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    /**
     * Returns the master-data version string the app compares against its local
     * InstalledVersion. Bulk tables are fetched separately over HTTP from the
     * resource endpoint; they are NOT carried in this response.
     *
     * <p>Source of truth = MasterDataStore.version() (the MasterDataSystemVersion.txt
     * content when a master dir is configured; else the config fallback).
     */
    @Override
    public void version(io.renagc.awanotsu.proto.masterdata.VersionRequest request, StreamObserver<io.renagc.awanotsu.proto.masterdata.VersionResponse> responseObserver) {
        // Return the store version, not the caller's x-master-version, so local
        // resource overrides can be delivered when the configured version changes.
        String clientVersion = io.renagc.awanotsu.auth.AuthInterceptor.CTX_MASTER_VERSION.get();
        String version = ctx.masterData().version();
        log.info("Masterdata.Version: client x-master-version={} -> returning {}",
                clientVersion, version);
        io.renagc.awanotsu.proto.masterdata.VersionResponse resp =
                io.renagc.awanotsu.proto.masterdata.VersionResponse.newBuilder()
                        .setVersion(version)
                        .build();
        responseObserver.onNext(resp);
        responseObserver.onCompleted();
    }

}
