package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.membercard.MemberCardService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class MemberCardServiceImpl extends io.renagc.awanotsu.proto.membercard.MemberCardServiceGrpc.MemberCardServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(MemberCardServiceImpl.class);

    private final ServerContext ctx;

    public MemberCardServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void awake(io.renagc.awanotsu.proto.membercard.AwakeRequest request, StreamObserver<io.renagc.awanotsu.proto.membercard.AwakeResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.membercard.AwakeResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void levelUp(io.renagc.awanotsu.proto.membercard.LevelUpRequest request, StreamObserver<io.renagc.awanotsu.proto.membercard.LevelUpResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.membercard.LevelUpResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void rankUp(io.renagc.awanotsu.proto.membercard.RankUpRequest request, StreamObserver<io.renagc.awanotsu.proto.membercard.RankUpResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.membercard.RankUpResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void skillLevelUp(io.renagc.awanotsu.proto.membercard.SkillLevelUpRequest request, StreamObserver<io.renagc.awanotsu.proto.membercard.SkillLevelUpResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.membercard.SkillLevelUpResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
