package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.mission.MissionService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class MissionServiceImpl extends io.renagc.awanotsu.proto.mission.MissionServiceGrpc.MissionServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(MissionServiceImpl.class);

    private final ServerContext ctx;

    public MissionServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void fetch(io.renagc.awanotsu.proto.mission.FetchMissionRequest request, StreamObserver<io.renagc.awanotsu.proto.mission.FetchMissionResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.mission.FetchMissionResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void receive(io.renagc.awanotsu.proto.mission.ReceiveRequest request, StreamObserver<io.renagc.awanotsu.proto.mission.ReceiveResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.mission.ReceiveResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void receiveCharacter(io.renagc.awanotsu.proto.mission.ReceiveCharacterRequest request, StreamObserver<io.renagc.awanotsu.proto.mission.ReceiveCharacterResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.mission.ReceiveCharacterResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void receiveLimited(io.renagc.awanotsu.proto.mission.ReceiveLimitedRequest request, StreamObserver<io.renagc.awanotsu.proto.mission.ReceiveLimitedResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.mission.ReceiveLimitedResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
