package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.pieceexchange.PieceExchangeService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class PieceExchangeServiceImpl extends io.renagc.awanotsu.proto.pieceexchange.PieceExchangeServiceGrpc.PieceExchangeServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(PieceExchangeServiceImpl.class);

    private final ServerContext ctx;

    public PieceExchangeServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void pieceExchange(io.renagc.awanotsu.proto.pieceexchange.PieceExchangeRequest request, StreamObserver<io.renagc.awanotsu.proto.pieceexchange.PieceExchangeResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.pieceexchange.PieceExchangeResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
