package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.player.PlayerService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class PlayerServiceImpl extends io.renagc.awanotsu.proto.player.PlayerServiceGrpc.PlayerServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(PlayerServiceImpl.class);

    private final ServerContext ctx;

    public PlayerServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void changeFavoriteMember(io.renagc.awanotsu.proto.player.ChangeFavoriteMemberRequest request, StreamObserver<io.renagc.awanotsu.proto.player.ChangeFavoriteMemberResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.player.ChangeFavoriteMemberResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void checkNgWord(io.renagc.awanotsu.proto.player.CheckNgWordRequest request, StreamObserver<io.renagc.awanotsu.proto.player.CheckNgWordResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.player.CheckNgWordResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void editProfile(io.renagc.awanotsu.proto.player.EditProfileRequest request, StreamObserver<io.renagc.awanotsu.proto.player.EditProfileResponse> responseObserver) {
        io.renagc.awanotsu.flow.Flows.editProfile(ctx, request, responseObserver);
    }

    @Override
    public void getConnectedPlayer(io.renagc.awanotsu.proto.player.GetConnectedPlayerRequest request, StreamObserver<io.renagc.awanotsu.proto.player.GetConnectedPlayerResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.player.GetConnectedPlayerResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void getPlayerData(io.renagc.awanotsu.proto.player.GetPlayerDataRequest request, StreamObserver<io.renagc.awanotsu.proto.player.GetPlayerDataResponse> responseObserver) {
        io.renagc.awanotsu.flow.Flows.getPlayerData(ctx, request, responseObserver);
    }

    @Override
    public void register(io.renagc.awanotsu.proto.player.RegisterRequest request, StreamObserver<io.renagc.awanotsu.proto.player.RegisterResponse> responseObserver) {
        var reg = ctx.players().register();
        io.renagc.awanotsu.proto.common.PlayerCredential cred =
                io.renagc.awanotsu.proto.common.PlayerCredential.newBuilder()
                        .setId(String.valueOf(reg.profileId()))
                        .setCredential(reg.credential())
                        .build();
        io.renagc.awanotsu.proto.player.RegisterResponse resp =
                io.renagc.awanotsu.proto.player.RegisterResponse.newBuilder()
                        .setCredential(cred)
                        .setProfileId(reg.profileId())
                        .build();
        responseObserver.onNext(resp);
        responseObserver.onCompleted();
    }

    @Override
    public void registerConnection(io.renagc.awanotsu.proto.player.RegisterConnectionRequest request, StreamObserver<io.renagc.awanotsu.proto.player.RegisterConnectionResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.player.RegisterConnectionResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void registerDevice(io.renagc.awanotsu.proto.player.RegisterDeviceRequest request, StreamObserver<io.renagc.awanotsu.proto.player.RegisterDeviceResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.player.RegisterDeviceResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void registerDeviceForConnectedPlayer(io.renagc.awanotsu.proto.player.RegisterDeviceForConnectedPlayerRequest request, StreamObserver<io.renagc.awanotsu.proto.player.RegisterDeviceForConnectedPlayerResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.player.RegisterDeviceForConnectedPlayerResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void removePlayerData(io.renagc.awanotsu.proto.player.RemovePlayerDataRequest request, StreamObserver<io.renagc.awanotsu.proto.player.RemovePlayerDataResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.player.RemovePlayerDataResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void whoami(io.renagc.awanotsu.proto.player.WhoamiRequest request, StreamObserver<io.renagc.awanotsu.proto.player.WhoamiResponse> responseObserver) {
        String authKey = io.renagc.awanotsu.auth.AuthInterceptor.CTX_AUTH_KEY.get();
        long profileId = ctx.players().resolveProfile(authKey);
        io.renagc.awanotsu.proto.player.WhoamiResponse resp =
                io.renagc.awanotsu.proto.player.WhoamiResponse.newBuilder()
                        .setPlayerId(String.valueOf(profileId))
                        .build();
        responseObserver.onNext(resp);
        responseObserver.onCompleted();
    }

}
