package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.present.PresentService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class PresentServiceImpl extends io.renagc.awanotsu.proto.present.PresentServiceGrpc.PresentServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(PresentServiceImpl.class);

    private final ServerContext ctx;

    public PresentServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void fetch(io.renagc.awanotsu.proto.present.FetchRequest request, StreamObserver<io.renagc.awanotsu.proto.present.FetchResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.present.FetchResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void history(io.renagc.awanotsu.proto.present.HistoryRequest request, StreamObserver<io.renagc.awanotsu.proto.present.HistoryResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.present.HistoryResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void open(io.renagc.awanotsu.proto.present.OpenRequest request, StreamObserver<io.renagc.awanotsu.proto.present.OpenResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.present.OpenResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
