package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.sendchat.SendChatService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class SendChatServiceImpl extends io.renagc.awanotsu.proto.sendchat.SendChatServiceGrpc.SendChatServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(SendChatServiceImpl.class);

    private final ServerContext ctx;

    public SendChatServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void sendChat(io.renagc.awanotsu.proto.sendchat.SendChatRequest request, StreamObserver<com.google.protobuf.Empty> responseObserver) {
        responseObserver.onNext(com.google.protobuf.Empty.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
