package io.renagc.awanotsu.service;

import io.grpc.BindableService;
import io.renagc.awanotsu.ServerContext;

import java.util.List;

/**
 * Auto-generated by tools/genservice.py. Returns one instance of every
 * generated *ServiceImpl, ready to register on the gRPC server.
 */
public final class ServiceRegistry {

    private ServiceRegistry() {
    }

    public static List<BindableService> all(ServerContext ctx) {
        return List.of(
                // --- NET-NEW binary-only services recovered from the IL2CPP dump ---
                new AnnouncementServiceImpl(ctx),
                new BandItemServiceImpl(ctx),
                new CarouselHelpServiceImpl(ctx),
                new CharacterServiceImpl(ctx),
                new CircleServiceImpl(ctx),
                new CircleInvitationServiceImpl(ctx),
                new CircleJoinRequestServiceImpl(ctx),
                new CircleMissionServiceImpl(ctx),
                // --- existing 28 services ---
                new CirclePlayerServiceImpl(ctx),
                new CircleRankingServiceImpl(ctx),
                new CircleRankUpRewardServiceImpl(ctx),
                new ContentUnlockServiceImpl(ctx),
                new DebugServiceImpl(ctx),
                new DeckServiceImpl(ctx),
                new EventServiceImpl(ctx),
                new ExchangeServiceImpl(ctx),
                new ExternalPaymentsServiceImpl(ctx),
                new FriendServiceImpl(ctx),
                new GachaServiceImpl(ctx),
                new HomeServiceImpl(ctx),
                new InvitationServiceImpl(ctx),
                new LiveServiceImpl(ctx),
                new LiveBoostServiceImpl(ctx),
                new LiveMusicServiceImpl(ctx),
                new LoginBonusServiceImpl(ctx),
                new MasterdataServiceImpl(ctx),
                new MemberCardServiceImpl(ctx),
                new MissionServiceImpl(ctx),
                new PieceExchangeServiceImpl(ctx),
                new PlayerServiceImpl(ctx),
                new PresentServiceImpl(ctx),
                new SendChatServiceImpl(ctx),
                new ShopServiceImpl(ctx),
                new StampServiceImpl(ctx),
                new StoryServiceImpl(ctx),
                new SupportCardServiceImpl(ctx)
        );
    }
}
