package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.shop.ShopService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class ShopServiceImpl extends io.renagc.awanotsu.proto.shop.ShopServiceGrpc.ShopServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(ShopServiceImpl.class);

    private final ServerContext ctx;

    public ShopServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void checkMaintenanceShop(io.renagc.awanotsu.proto.shop.CheckMaintenanceShopRequest request, StreamObserver<io.renagc.awanotsu.proto.shop.CheckMaintenanceShopResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.shop.CheckMaintenanceShopResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void fetch(io.renagc.awanotsu.proto.shop.FetchRequest request, StreamObserver<io.renagc.awanotsu.proto.shop.FetchResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.shop.FetchResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void history(io.renagc.awanotsu.proto.shop.HistoryRequest request, StreamObserver<io.renagc.awanotsu.proto.shop.HistoryResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.shop.HistoryResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void purchase(io.renagc.awanotsu.proto.shop.PurchaseRequest request, StreamObserver<io.renagc.awanotsu.proto.shop.PurchaseResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.shop.PurchaseResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void purchaseCash(io.renagc.awanotsu.proto.shop.PurchaseCashRequest request, StreamObserver<com.google.protobuf.Empty> responseObserver) {
        responseObserver.onNext(com.google.protobuf.Empty.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void purchaseCM(io.renagc.awanotsu.proto.shop.PurchaseCMRequest request, StreamObserver<com.google.protobuf.Empty> responseObserver) {
        responseObserver.onNext(com.google.protobuf.Empty.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void saveBirth(io.renagc.awanotsu.proto.shop.SaveBirthRequest request, StreamObserver<io.renagc.awanotsu.proto.shop.SaveBirthResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.shop.SaveBirthResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
