package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.stamp.StampService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class StampServiceImpl extends io.renagc.awanotsu.proto.stamp.StampServiceGrpc.StampServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(StampServiceImpl.class);

    private final ServerContext ctx;

    public StampServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void updateStampFavoriteName(io.renagc.awanotsu.proto.stamp.UpdateStampFavoriteNameRequest request, StreamObserver<io.renagc.awanotsu.proto.stamp.UpdateStampFavoriteNameResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.stamp.UpdateStampFavoriteNameResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void updateStampFavorites(io.renagc.awanotsu.proto.stamp.UpdateStampFavoritesRequest request, StreamObserver<io.renagc.awanotsu.proto.stamp.UpdateStampFavoritesResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.stamp.UpdateStampFavoritesResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
