package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.story.StoryService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class StoryServiceImpl extends io.renagc.awanotsu.proto.story.StoryServiceGrpc.StoryServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(StoryServiceImpl.class);

    private final ServerContext ctx;

    public StoryServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void checkMaintenanceStory(io.renagc.awanotsu.proto.story.CheckMaintenanceStoryRequest request, StreamObserver<io.renagc.awanotsu.proto.story.CheckMaintenanceStoryResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.story.CheckMaintenanceStoryResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void readFriendshipEpisode(io.renagc.awanotsu.proto.story.ReadFriendshipEpisodeRequest request, StreamObserver<io.renagc.awanotsu.proto.story.ReadFriendshipEpisodeResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.story.ReadFriendshipEpisodeResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void readStoryEpisode(io.renagc.awanotsu.proto.story.ReadStoryEpisodeRequest request, StreamObserver<io.renagc.awanotsu.proto.story.ReadStoryEpisodeResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.story.ReadStoryEpisodeResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
