package io.renagc.awanotsu.service;

import io.grpc.stub.StreamObserver;
import io.renagc.awanotsu.ServerContext;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * gRPC impl for app.supportcard.SupportCardService.
 * Auto-generated by tools/genservice.py.
 *
 * <p>Default methods return the default response instance (NOT UNIMPLEMENTED)
 * so the channel stays usable. Boot-critical methods have real bodies.
 */
public final class SupportCardServiceImpl extends io.renagc.awanotsu.proto.supportcard.SupportCardServiceGrpc.SupportCardServiceImplBase {

    private static final Logger log = LoggerFactory.getLogger(SupportCardServiceImpl.class);

    private final ServerContext ctx;

    public SupportCardServiceImpl(ServerContext ctx) {
        this.ctx = ctx;
    }

    @Override
    public void levelUp(io.renagc.awanotsu.proto.supportcard.LevelUpRequest request, StreamObserver<io.renagc.awanotsu.proto.supportcard.LevelUpResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.supportcard.LevelUpResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

    @Override
    public void rankUp(io.renagc.awanotsu.proto.supportcard.RankUpRequest request, StreamObserver<io.renagc.awanotsu.proto.supportcard.RankUpResponse> responseObserver) {
        responseObserver.onNext(io.renagc.awanotsu.proto.supportcard.RankUpResponse.getDefaultInstance());
        responseObserver.onCompleted();
    }

}
